title: Typozine
description: ""
footer_text: Copyright 2021 Hannah Doherty
header_feature_image: ../uploads/charisse-kenion-cjkvmakdyl0-unsplash.jpg
header_text: ""
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
