title: Typozine
description: ""
footer_text: Copyright 2021 Hannah Doherty
header_feature_image: ../uploads/untitled-2.png
header_text: ""
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 35px
logo: ../uploads/logo.png
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
