title: Typozine
description: ""
footer_text: Copyright 2021 Hannah Doherty
header_feature_image: ../uploads/untitled-3.png
header_text: ""
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/untitled-1.png
favicon: ../uploads/android-chrome-512x512.png
gridlayout: true
fixednavbar: true
upzoom: true
items:
  - name: About Author
    siteurl: /aboutme
    tab: false
